const actionType = {
  GET_ACCOUNTS_LOADING : 'GET_ACCOUNTS_LOADING',
  GET_ACCOUNTS_ERROR : 'GET_ACCOUNTS_ERROR',
  GET_ACCOUNTS_SUCCESS : 'GET_ACCOUNTS_SUCCESS',
  GET_OWNERDETAILS_LOADING : 'GET_OWNERDETAILS_LOADING',
  GET_OWNERDETAILS_ERROR : 'GET_OWNERDETAILS_ERROR',
  GET_OWNERDETAILS_SUCCESS : 'GET_OWNERDETAILS_SUCCESS',
  GET_ALL_BOOKS_LOADING : 'GET_ALL_BOOKS_LOADING',
  GET_ALL_BOOKS_ERROR : 'GET_ALL_BOOKS_ERROR',
  GET_ALL_BOOKS_SUCCESS : 'GET_ALL_BOOKS_SUCCESS',
  GET_MY_BOOKS_LOADING : 'GET_MY_BOOKS_LOADING',
  GET_MY_BOOKS_ERROR : 'GET_MY_BOOKS_ERROR',
  GET_MY_BOOKS_SUCCESS : 'GET_MY_BOOKS_SUCCESS',
  GET_ADD_BOOKS_LOADING : 'GET_ADD_BOOKS_LOADING',
  GET_ADD_BOOKS_ERROR : 'GET_ADD_BOOKS_ERROR',
  GET_ADD_BOOKS_SUCCESS : 'GET_ADD_BOOKS_SUCCESS',
  GET_RETURN_BOOKS_LOADING : 'GET_RETURN_BOOKS_LOADING',
  GET_RETURN_BOOKS_ERROR : 'GET_RETURN_BOOKS_ERROR',
  GET_RETURN_BOOKS_SUCCESS : 'GET_RETURN_BOOKS_SUCCESS',
  GET_BORROW_BOOKS_LOADING : 'GET_BORROW_BOOKS_LOADING',
  GET_BORROW_BOOKS_ERROR : 'GET_BORROW_BOOKS_ERROR',
  GET_BORROW_BOOKS_SUCCESS : 'GET_BORROW_BOOKS_SUCCESS',
  SEARCH_BOOK : 'SEARCH_BOOK',
  RATE_BOOK_LOADING : 'RATE_BOOK_LOADING',
  RATE_BOOK_ERROR : 'RATE_BOOK_ERROR',
  RATE_BOOK_SUCCESS : 'RATE_BOOK_SUCCESS'
}

export default actionType
